import HeroArt from './HeroArt';

const live = process.env.VEYRO_LIVE_URL || '#demo';
export default function Home() { return <>
<header><a className="wordmark" href="/" aria-label="Veyro home"><span className="mark">v</span>veyro<span className="word-dot">®</span></a><nav><a href="#how">How it works</a><a href="https://github.com/veyro-real/veyro-protocol">The protocol</a><a href="https://github.com/veyro-real/veyro-live">Developers ↗</a></nav><a className="button small" href={live}>Explore Veyro <span>↗</span></a></header>
<main><section className="hero"><div className="eyebrow"><span className="pulse"/> AUTONOMOUS MONEY. HUMAN CONTROL.</div><h1>Your agent.<br/>Your money.<br/><em>Your rules.</em></h1><div className="hero-bottom"><p>Tell it what you want. Set the limits.<br/>Let it work.</p><a className="button" href={live}>Meet your next move <span>↗</span></a></div><HeroArt/><div className="hero-foot"><span>BUILT NATIVELY ON <b>≋ Solana</b></span><span>01 / THE NEXT WAY MONEY MOVES</span></div></section>
<section id="how" className="how"><div className="section-heading"><span className="eyebrow">LESS MICROMANAGING. MORE CONTROL.</span><h2>Give it a direction.<br/>Keep the boundaries.</h2></div><div className="steps"><article><span className="step">01</span><h3>Say the word.</h3><p>Start with an intent. Your agent turns what you want into a proposed action.</p><div className="snippet">“Find the dumbest meme coin.” <span>↗</span></div></article><article><span className="step">02</span><h3>Draw the line.</h3><p>Choose its budget, allowed actions and expiration. Your permission has a limit.</p><div className="snippet">Up to 100 USDC <span>◎</span></div></article><article><span className="step">03</span><h3>Let it work.</h3><p>The protocol checks before funds move. Follow the result, or revoke access.</p><div className="snippet">Policy checked. Action recorded. <span>✓</span></div></article></div></section>
<section id="demo" className="demo"><div><span className="eyebrow">THE FIRST DEMO</span><h2>A little chaos.<br/><em>A hard limit.</em></h2><p>An agent hunts for a meme coin. You give it a budget. Veyro enforces the boundary.</p><p className="muted">The demo uses valueless test tokens on Solana testnet and a controlled swap pool. Research fixtures and real X results are labeled separately.</p><a className="button" href={process.env.VEYRO_LIVE_URL || 'https://github.com/veyro-real/veyro-live'}>{process.env.VEYRO_LIVE_URL ? 'Open the live demo' : 'Explore the demo repository'} ↗</a></div><div className="decision-board"><div className="board-head"><span>VE Y R O / POLICY CHECK</span><span className="pill">TESTNET DEMO</span></div><div className="decision-row"><span>Approved route · within budget</span><b className="allow">ALLOW ↗</b></div><div className="decision-row"><span>Purchase exceeds spending cap</span><b className="deny">DENY ⊘</b></div><div className="decision-row"><span>Destination not approved</span><b className="deny">DENY ⊘</b></div><div className="decision-row"><span>Agent permission revoked</span><b className="deny">DENY ⊘</b></div><p>Illustrative outcomes. The live app shows actual execution status and transaction receipts.</p></div></section>
<section id="protocol" className="protocol"><span className="eyebrow">FOR BUILDERS</span><h2>Let agents move money.<br/>Make permission explicit.</h2><div className="protocol-grid"><p>A Solana authorization layer for delegated spending. On-chain budgets, scoped actions, revocation and an inspectable attempt trail.</p><div><code>@veyro/sdk</code><code>@veyro/core</code><a href="https://github.com/veyro-real/veyro-protocol">Explore the protocol ↗</a></div></div><div className="disclosure">Early testnet software. Spending controls do not assess token legitimacy, guarantee returns or protect funds after an approved transfer. No mainnet deployment.</div></section>
</main><footer><a className="wordmark" href="/">veyro</a><span>Tell it what you want. Set the limits. Let it work.</span><a href="https://github.com/veyro-real">GitHub ↗</a></footer></> }
